export default {
    SPLASH_LOGO: require('../assets/images/surfica_splash_logo.png'),
    CARPENTER: require('../assets/images/role_carpenter.png'),
    ARCHITECT: require('../assets/images/role_architect.png'),
    USER: require('../assets/images/signup_user.png'),
    PHONE: require('../assets/images/signup_phone.png'),
    EMAIL: require('../assets/images/signup_email.png'),
    PASSWORD: require('../assets/images/signup_password.png'),
    CHECK: require('../assets/images/check.png'),
    HOME: require('../assets/images/home_icon.png'),
    RECOMMENDATION: require('../assets/images/transaction_icon.png'),
    PROFILE: require('../assets/images/profile_icon.png'),
    BACK: require('../assets/images/ic_back.png'),
    DRAWER:require('../assets/images/menu_icon.png'),
    SURFICA_LOGO:require('../assets/images/logo_header.png'),
    SURFICA_LOGO_1:require('../assets/images/header_logo_trimmed.png'),
    SHARE:require('../assets/images/ic_forward.png'),
    ARROW_RIGHT:require('../assets/images/dropdown.png'),
    PRIVACY:require('../assets/images/Policy.png'),
    CONTACT_US:require('../assets/images/contact_icon.png'),
    LOGOUT:require('../assets/images/logout_icon.png'),
    FB:require('../assets/images/fb.png'),
    INSTA:require('../assets/images/insta.png'),
    LINKEDIN:require('../assets/images/linked.png'),
    TWITTER:require('../assets/images/tweet.png'),
    SCAN:require('../assets/images/scan_icon.png'),
    CHECKED:require('../assets/images/ic_checked.png'),
    LAMINATE_1:require('../assets/images/laminate_1.jpeg'),
    LAMINATE_2:require('../assets/images/laminate_2.jpeg'),
    LAMINATE_3:require('../assets/images/laminate_3.jpeg'),
    LAMINATE_4:require('../assets/images/laminate_4.jpeg'),
    LAMINATE_5:require('../assets/images/laminate_5.jpeg'),
    LAMINATE_6:require('../assets/images/laminate_6.jpeg'),
    LAMINATE_7:require('../assets/images/laminate_7.jpeg'),
    LAMINATE_8:require('../assets/images/laminate_8.jpeg'),
    FILTER:require('../assets/images/filter.png'),
    CANCEL:require('../assets/images/ic_cancel.png'),
    HOME_SURFICA:require('../assets/images/surfica_trimmed.png'),
    HOME_SLIMICA:require('../assets/images/slimica_icon.png'),
    HOME_INNOVICA:require('../assets/images/innovica_icon.png'),
    QR_SCANNER:require('../assets/images/qr_code.png'),
    VIEW:require('../assets/images/view.png'),
    HIDDEN:require('../assets/images/hidden.png'),
    ABOUT:require('../assets/images/about_icon.png'),
    WITHDRAW:require('../assets/images/withdrawal.png'),
    CATALOG:require('../assets/images/catalog.png'),
    PICK_IMAGE:require('../assets/images/ic_camera.png'),
    PICK_GALLERY:require('../assets/images/ic_gallery.png'),
    REFFERS:require('../assets/images/ic_recommendations.png'),
    LOGO_DARK:require('../assets/images/company_logo_dark.png'),
    CAROUSEL_1:require('../assets/images/carousel_image_1.jpeg'),
    CAROUSEL_2:require('../assets/images/carousel_image_2.jpeg'),
    CAROUSEL_3:require('../assets/images/carousel_image_3.jpeg'),
}