export default {
    SIGNUP: 'Sign up',
    SIGNUP1: 'Sign Up',
    AS: 'As',
    CARPENTER: 'Carpenter',
    ARCHITECT: 'Architect',
    FILL_DETAILS: 'Fill the details & create your account',
    FULL_NAME: 'Full Name',
    CITY: 'City',
    MOBILE_NO: 'Mobile No.',
    EMAIL: 'Email',
    PASSWORD: 'Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    TERM_CONDITION: 'Terms & Conddition',
    PROCESSING: 'Processing',
    CONTACT_US: 'Contacts Us',
    SCAN_VERIFY: 'Scan & Verify',
    REDEEM_POINT: 'Redeem Your Points',
    GET_OFFER: 'Get Exciting Offers',
    LETS_START: "Let's Start",
    SIGNIN: 'Sign In',
    LOGIN_WITH_OTP: 'LOGIN WITH OTP',
    FORGOT_PASSWORD: 'Forgot Password?',
    FORGOT_PASSWORD1: 'Forgot Password',
    DONT_HAVE_ACCOUNT: "Don't have an account?",
    ALREADY_HAVE_ACCOUNT: "Already have an account?",
    TOTAL: 'Total',
    SCAN: 'Scan',
    LAST7DAY: 'Points earned',
    WITHDRAW: 'Withdraw',
    HISTORY: 'History',
    BROWSE_LIMINATE: 'Browse Our Catalogs',
    FILTERS: 'Filters',
    BY_CATALOG: 'Catalog',
    BY_COLOR: 'Color',
    BY_FINISH: 'Finish',
    EDIT_PROFILE: 'Edit Profile',
    NAME: 'Name',
    DOB: 'DOB',
    STATE: 'State',
    PHONE: 'Phone',
    ACCOUNT_HOLDER_NAME: 'Account Holder Name',
    IFSC_CODE: 'IFSC Code',
    BANK_NAME: 'Bank Name',
    ACCOUNT_NUMBER: 'Account Number',
    ACCOUNT_TYPE: 'Account Type',
    UPI_NUMBER: 'UPI Number',
    UPDATE: 'Update',
    HELP: 'Help',
    ABOUT: 'About surfica',
    TNC_PP: 'T&C and Policies',
    LOGOUT: 'Logout',
    RECOMMENDATION: 'Recommendations',
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    MESSAGE: 'Message',
    WRITE_MESSAGE: 'Write your message here',
    SEND: 'Send',
    TRANSACTION:'Transactions',
    PERSONAL_DETAILS:'Personal Details',
    BANK_DETAILS:'Bank Details',
    CUSTOMER_DETAILS:'Customer Details',
    CUSTOMER_NAME:'Customer Name',
    PROPERTY_TYPE:'Property Type',
    PROPOSED_QTY:'Proposed Qty',
    SUBMIT:'Submit',
    SAVE:'Save',
    VERIFY:'Verify',
    SURFICA_CATEGORY:'Surfica',
    LINICA_CATEGORY:'Linica',
    INNOVICA_CATEGORY:'Innovica',
    FORM_ERROR:'Error',
    ENTER_FULLNAME:'Please enter the fullname',
    ENTER_CITY:'Please select the city',
    ENTER_STATE:'Please select the state',
    ENTER_MOBILE_NO:'Please enter the mobile number',
    ENTER_VALID_MOBILE_NO:'Please enter the valid mobile numberr',
    ENTER_PASSWORD:'Please enter the password',
    ENTER_CONFIRM_PASSWORD:'Please enter the confirm password',
    PASSWORD_NOT_SAME:'Confirm password is must be same',
    ACCEPT_TERMS:'Please accept terms & condition',
    ENTER_EMAIL:'Please enter the email',
    ENTER_VALID_EMAIL:'Please enter the valid email',
    ENTER_DOB:'Please select the DOB',
    ENTER_ACCOUNT_TYPE:'Please select the account type',
    ENTER_BANK_NAME:'Please enter the bank name',
    ENTER_ACCOUNT_HOLDER:'Please enter the account holder name',
    ENTER_IFSC_CODE:'Please enter the IFSC code',
    ENTER_ACCOUNT_NUMBER:'Please enter the account number',
    ENTER_CUSTOMER_NAME:'Please enter the customer name',
    ENTER_PROPERTY_TYPE:'Please select the property type',
    ENTER_PROPOSED_QTY:'Please enter the proposed qty',
    ENTER_FIRST_NAME:'Please enter the first name',
    ENTER_LAST_NAME:'Please enter the last name',
    ENTER_MESSAGE:'Please enter the message',
    PRODUCT: 'Product',
    CLIENT_DIRECTORY:'Client Directory'

}